name: Github 
on: push
jobs: 
  Explore-github:
    runs-on: ubuntu-latest 
    steps:
    - name: Print the triggering event
      run: echo "The job was triggered by ${{ github.event_name }}."
    - name: Print the branch name that the workflow runs on
      run: echo "The name of your branch is ${{ github.ref }} ."
    - name: Check out repository code action
      uses: actions/checkout@v4
 
